### ISSUE TITLE
npm start fails: "It's not clear which file to import"

### ISSUE THREAD

**Issue by dmnd** [akiran/react-slick#201]
```
$ node -v
v5.0.0

$ npm -v
3.5.1

$ git log -n1
commit de5b832d02aa6092cac8f2fba75e49cff9b48c1a
Author: Kiran <akiran@users.noreply.github.com>
Date:   Sat Dec 5 22:05:20 2015 +0530

    Update README.md

$ npm start

> react-slick@0.9.3 start /Users/desmondbrand/github/react-slick
> gulp server

[14:36:02] Using gulpfile ~/github/react-slick/gulpfile.js
[14:36:02] Starting 'copy'...
[14:36:02] Starting 'sass'...
[14:36:02] Finished 'copy' after 42 ms

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: docs/docs.scss
Error: It's not clear which file to import for '@import "slick-carousel/slick/slick"'.
       Candidates:
         slick-carousel/slick/slick.scss
         slick-carousel/slick/slick.css
       Please delete or rename all but one of these files.
        on line 8 of stdin
>> @import "slick-carousel/slick/slick";
   ^

    at options.error (/Users/desmondbrand/github/react-slick/node_modules/node-sass/lib/index.js:277:32)

npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/desmondbrand/.nvm/versions/node/v5.0.0/bin/node" "/Users/desmondbrand/.nvm/versions/node/v5.0.0/bin/npm" "start"
npm ERR! node v5.0.0
npm ERR! npm  v3.5.1
npm ERR! code ELIFECYCLE
npm ERR! react-slick@0.9.3 start: `gulp server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-slick@0.9.3 start script 'gulp server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-slick package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-slick
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-slick
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/desmondbrand/github/react-slick/npm-debug.log
```

Here's npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/desmondbrand/.nvm/versions/node/v5.0.0/bin/node',
1 verbose cli   '/Users/desmondbrand/.nvm/versions/node/v5.0.0/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.5.1
3 info using node@v5.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle react-slick@0.9.3~prestart: react-slick@0.9.3
6 silly lifecycle react-slick@0.9.3~prestart: no script for prestart, continuing
7 info lifecycle react-slick@0.9.3~start: react-slick@0.9.3
8 verbose lifecycle react-slick@0.9.3~start: unsafe-perm in lifecycle true
9 verbose lifecycle react-slick@0.9.3~start: PATH: /Users/desmondbrand/.nvm/versions/node/v5.0.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/desmondbrand/github/react-slick/node_modules/.bin:/Users/desmondbrand/.nvm/versions/node/v5.0.0/bin:/Users/desmondbrand/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/desmondbrand/bin:/Users/desmondbrand/github/arcanist/bin
10 verbose lifecycle react-slick@0.9.3~start: CWD: /Users/desmondbrand/github/react-slick
11 silly lifecycle react-slick@0.9.3~start: Args: [ '-c', 'gulp server' ]
12 silly lifecycle react-slick@0.9.3~start: Returned: code: 1  signal: null
13 info lifecycle react-slick@0.9.3~start: Failed to exec start script
14 verbose stack Error: react-slick@0.9.3 start: `gulp server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/desmondbrand/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/desmondbrand/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid react-slick@0.9.3
16 verbose cwd /Users/desmondbrand/github/react-slick
17 error Darwin 15.2.0
18 error argv "/Users/desmondbrand/.nvm/versions/node/v5.0.0/bin/node" "/Users/desmondbrand/.nvm/versions/node/v5.0.0/bin/npm" "start"
19 error node v5.0.0
20 error npm  v3.5.1
21 error code ELIFECYCLE
22 error react-slick@0.9.3 start: `gulp server`
22 error Exit status 1
23 error Failed at the react-slick@0.9.3 start script 'gulp server'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-slick package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp server
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-slick
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-slick
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by akiran** [comment]
I guess, this is the problem with node-sass 
http://stackoverflow.com/questions/33612388/how-to-address-node-sass-regression-its-not-clear-which-file-to-import-for
