### ISSUE TITLE
Gatsby build  ERROR #98123  WEBPACK Generating JavaScript bundles failed

### ISSUE THREAD

**Issue by PhilippLiebhart** [akiran/react-slick#2025]
Hi Folks!
gatsby newb here ^^
i am currently working on a gatsby site... in development everything works fine but when i try to build it's throwing this error and i can't even figure out where it could be coming from :(

`
ERROR #98123 WEBPACK

Generating JavaScript bundles failed

styles.4fb9bf79ef56fd3e22c1.css from Css Minimizer
/Users/philos/Documents/_PROJECTS/APPs/projectFolder/styles.4fb9bf79ef56fd3e22c1.css:139:5: Unknown word [styles.4fb9bf79ef56fd3e22c1.css:139,5]
at Input.error (/Users/philos/Documents/_PROJECTS/APPs/projectFolder/node_modules/cssnano/node_modules/postcss/lib/input.js:128:16)
at Parser.unknownWord (/Users/philos/Documents/_PROJECTS/APPs/projectFolder/node_modules/cssnano/node_modules/postcss/lib/parser.js:561:22)
at Parser.other (/Users/philos/Documents/_PROJECTS/APPs/projectFolder/node_modules/cssnano/node_modules/postcss/lib/parser.js:166:12)
at Parser.parse (/Users/philos/Documents/_PROJECTS/APPs/projectFolder/node_modules/cssnano/node_modules/postcss/lib/parser.js:75:16)
at parse (/Users/philos/Documents/_PROJECTS/APPs/projectFolder/node_modules/cssnano/node_modules/postcss/lib/parse.js:17:12)
at new LazyResult (/Users/philos/Documents/_PROJECTS/APPs/projectFolder/node_modules/cssnano/node_modules/postcss/lib/lazy-result.js:64:16)
at Processor. (/Users/philos/Documents/_PROJECTS/APPs/projectFolder/node_modules/cssnano/node_modules/postcss/lib/processor.js:142:12)
at Processor.process (/Users/philos/Documents/_PROJECTS/APPs/projectFolder/node_modules/cssnano/node_modules/postcss/lib/processor.js:121:23)
at Function.creator.process (/Users/philos/Documents/_PROJECTS/APPs/projectFolder/node_modules/cssnano/node_modules/postcss/lib/postcss.js:148:43)
at minify (/Users/philos/Documents/_PROJECTS/APPs/projectFolder/node_modules/css-minimizer-webpack-plugin/dist/minify.js:102:32)`

its building when i comment out the react-slick css files...
`import "slick-carousel/slick/slick.css"
import "slick-carousel/slick/slick-theme.css"`

hope somebody can help!
thanks in advance and have a great day!

**Comment by akiran** [comment]
Do you have "slick-carousel"  in dependencies list of package.json?

**Comment by PhilippLiebhart** [comment]
@akiran yes i have  "slick-carousel": "^1.8.1"

**Comment by PhilippLiebhart** [comment]
i commented out all imports in the specific components and added the css like this.. in the index.js .. working for now!
but i don't know if this should be the way to go..

`  <Helmet>
        <link
          rel="stylesheet"
          type="text/css"
          charset="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </Helmet>`
