### ISSUE TITLE
Snowpack release builds fail

### ISSUE THREAD

**Issue by Burny-McBurnFace** [akiran/react-slick#2113]
When using a snowpack project and building in release it uses esbuild, but this dependency causes the build to fail because of the CSS urls:

```
[22:28:33] [snowpack] ! optimizing build...
 > build/_snowpack/pkg/slick-carousel/slick/slick-theme.css:5:25: error: Could not resolve "./ajax-loader.gif"
    5 │     background: #fff url('./ajax-loader.gif') center center no-repeat;
      ╵                          ~~~~~~~~~~~~~~~~~~~

 > build/_snowpack/pkg/slick-carousel/slick/slick-theme.css:15:13: error: Could not resolve "./fonts/slick.eot"
    15 │     src: url('./fonts/slick.eot');
       ╵              ~~~~~~~~~~~~~~~~~~~

 > build/_snowpack/pkg/slick-carousel/slick/slick-theme.css:16:13: error: Could not resolve "./fonts/slick.eot?#iefix"
    16 │     src: url('./fonts/slick.eot?#iefix') format('embedded-opentype'), url('./fonts/slick.woff') format('woff'), url('./fonts/slick.ttf') format('t...
       ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~

 > build/_snowpack/pkg/slick-carousel/slick/slick-theme.css:16:74: error: Could not resolve "./fonts/slick.woff"
    16 │ ...('./fonts/slick.eot?#iefix') format('embedded-opentype'), url('./fonts/slick.woff') format('woff'), url('./fonts/slick.ttf') format('truetype')...
       ╵                                                                  ~~~~~~~~~~~~~~~~~~~~

 > build/_snowpack/pkg/slick-carousel/slick/slick-theme.css:16:116: error: Could not resolve "./fonts/slick.ttf"
    16 │ ...ded-opentype'), url('./fonts/slick.woff') format('woff'), url('./fonts/slick.ttf') format('truetype'), url('./fonts/slick.svg#slick') format('s...
       ╵                                                                  ~~~~~~~~~~~~~~~~~~~

 > build/_snowpack/pkg/slick-carousel/slick/slick-theme.css:16:161: error: Could not resolve "./fonts/slick.svg#slick"
    16 │ ...d-opentype'), url('./fonts/slick.woff') format('woff'), url('./fonts/slick.ttf') format('truetype'), url('./fonts/slick.svg#slick') format('svg');
       ╵                                                                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~

[22:28:33] [snowpack] Build failed with 6 errors:
build/_snowpack/pkg/slick-carousel/slick/slick-theme.css:5:25: error: Could not resolve "./ajax-loader.gif"
build/_snowpack/pkg/slick-carousel/slick/slick-theme.css:15:13: error: Could not resolve "./fonts/slick.eot"
build/_snowpack/pkg/slick-carousel/slick/slick-theme.css:16:13: error: Could not resolve "./fonts/slick.eot?#iefix"
build/_snowpack/pkg/slick-carousel/slick/slick-theme.css:16:74: error: Could not resolve "./fonts/slick.woff"
build/_snowpack/pkg/slick-carousel/slick/slick-theme.css:16:116: error: Could not resolve "./fonts/slick.ttf"
...
[22:28:33] [snowpack] Error: Build failed with 6 errors:
build/_snowpack/pkg/slick-carousel/slick/slick-theme.css:5:25: error: Could not resolve "./ajax-loader.gif"
build/_snowpack/pkg/slick-carousel/slick/slick-theme.css:15:13: error: Could not resolve "./fonts/slick.eot"
build/_snowpack/pkg/slick-carousel/slick/slick-theme.css:16:13: error: Could not resolve "./fonts/slick.eot?#iefix"
build/_snowpack/pkg/slick-carousel/slick/slick-theme.css:16:74: error: Could not resolve "./fonts/slick.woff"
build/_snowpack/pkg/slick-carousel/slick/slick-theme.css:16:116: error: Could not resolve "./fonts/slick.ttf"
...
    at failureErrorWithLog (/home/burny/my_project/node_modules/esbuild/lib/main.js:1224:15)
    at buildResponseToResult (/home/burny/my_project/node_modules/esbuild/lib/main.js:936:32)
    at /home/burny/my_project/node_modules/esbuild/lib/main.js:1035:20
    at /home/burny/my_project/node_modules/esbuild/lib/main.js:568:9
    at handleIncomingPacket (/home/burny/my_project/node_modules/esbuild/lib/main.js:657:9)
    at Socket.readFromStdout (/home/burny/my_project/node_modules/esbuild/lib/main.js:535:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

Please suggest how to fix this or if I can add some more information to this issue.  Thanks.

**Comment by akiran** [comment]
This is not an issue with this library
