### ISSUE TITLE
sass %1 is not a valid win32 application

### ISSUE THREAD

**Issue by yursile** [akiran/react-slick#250]
when i run npm install, i have this error:
Error: %1 is not a valid Win32 application.
\\?\D:\webjar\react-slick-master\node_modules\node-sass\vendor\win32-x64-47\bind
ing.node
    at Error (native)
    at Object.Module._extensions..node (module.js:422:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\webjar\react-slick-master\node_modules\node-sass\l
ib\index.js:16:15)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)

i'm wondering both of my os and node are 64bit, and there is no one except me have this problem.
please help!!

**Comment by akiran** [comment]
This is not an issue with react-slick.

Could be an issue with node-sass.
