### ISSUE TITLE
Page load delayed styling and positioning

### ISSUE THREAD

**Issue by brandon-arnold** [akiran/react-slick#537]
This is not the kind of issue I can demonstrate with a js-fiddle.

When the page loads, there are 1-5 seconds where elements are stacked weird. It depends on the framework, but it happened with React-Bootstrap also; now it's React-Slick. You can see it now on my website if you will navigate to [brandonarnold.com](https://www.brandonarnold.com).

Any thoughts about what would cause this delay?

It is clearly a delay of the styling being related to my DOM content. Here's how the CDN is linked in my HTML head tags:

```html
<link href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css" rel="stylesheet" />
```

Here is how I import the component:

```javascript
import Slider from 'react-slick';
```

Settings for Slider:

```javascript
    this.slSettings = {
      dots: true,
      infinite: false,
      speed: 500,
      autoplay: false,
      arrows: false,
      slidesToShow: 1,
      slidesToScroll: 1
    };
```

Render snippet of React component:

```javascript
<Slider {...this.slSettings}>
  {this.chessGameSections} // a list of <div>...</div> elements
</Slider>
```

**Comment by brandon-arnold** [comment]
I'm pretty sure it's because the CSS is being downloaded on page load instead of being rendered inline by Webpack. So far I have been able to copy the above CSS files into my project but have been unsuccessful in getting them to be downloaded before the other content.

**Comment by brandon-arnold** [comment]
Nope. It has nothing to do with download times of CSS or fonts. I now have all my custom fonts disabled, and I have ```slick.css``` and ```slick-theme.css``` being generated inline in <scripts> in the <head> of my HTML document. The startup delay persists.

**Comment by akiran** [comment]
Is is because you are doing server side rendering.
I will try to fix

**Comment by brandon-arnold** [comment]
@akiran Maybe I can help. I just cloned from ```master``` however and when I run ```gulp server``` it fails. Apparently it is trying to process the JSX files as node javascript and fails to parse the HTML tags. How is it running on your system and not mine? Why'd you change the filenames from JSX to JS?

The following is the first error on the SimpleSlider.js file, but there is a similar error for all JSX files:

```bash
Module parse failed: C:\projects\bacom\node_modules\react-slick\examples\SimpleSlider.js Unexpected token (14:6)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (14:6)
    at Parser.pp$4.raise (C:\projects\bacom\node_modules\react-slick\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\projects\bacom\node_modules\react-slick\node_modules\webpack\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (C:\projects\bacom\node_modules\react-slick\node_modules\webpack\node_modules\acorn\dist\acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (C:\projects\bacom\node_modules\react-slick\node_modules\webpack\node_modules\acorn\dist\acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (C:\projects\bacom\node_modules\react-slick\node_modules\webpack\node_modules\acorn\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (C:\projects\bacom\node_modules\react-slick\node_modules\webpack\node_modules\acorn\dist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (C:\projects\bacom\node_modules\react-slick\node_modules\webpack\node_modules\acorn\dist\acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (C:\projects\bacom\node_modules\react-slick\node_modules\webpack\node_modules\acorn\dist\acorn.js:1597:21)
    at Parser.pp$3.parseParenAndDistinguishExpression (C:\projects\bacom\node_modules\react-slick\node_modules\webpack\node_modules\acorn\dist\acorn.js:1861:32)
    at Parser.pp$3.parseExprAtom (C:\projects\bacom\node_modules\react-slick\node_modules\webpack\node_modules\acorn\dist\acorn.js:1796:19)
 @ ./docs/demos.jsx 13:20-55
```

**Comment by Anshul-HL** [comment]
Facing the same issue. Initially all the divisions are stacked one over the other and after a lag of 5-6 sec, the slider works with all the styles applied.

Any updates regarding this?

**Comment by dcurletti** [comment]
Also having this issue when server side rendering.

**Comment by laveesingh** [comment]
The issue was there in ssr. A fix has been implemented to use temporary styling until js kicks in with componentDidMount. The fix is still in dev mode, will be released soon.

**Comment by annarichardson** [comment]
When will this be fixed?
