### ISSUE TITLE
compile error when require slick component

### ISSUE THREAD

**Issue by ibcLee** [akiran/react-slick#587]
```
ERROR in ./~/react-slick/src/slider.js
    Module parse failed: /Users/Libbbbc/works/circle-web/node_modules/react-slick/src/slider.js Unexpected token (82:8)
    You may need an appropriate loader to handle this file type.
    SyntaxError: Unexpected token (82:8)
        at Parser.pp.raise (/Users/Libbbbc/works/circle-web/node_modules/.npminstall/acorn/3.1.0/acorn/dist/acorn.js:920:13)
        at Parser.pp.unexpected (/Users/Libbbbc/works/circle-web/node_modules/.npminstall/acorn/3.1.0/acorn/dist/acorn.js:1483:8)
        at Parser.pp.parseExprAtom (/Users/Libbbbc/works/circle-web/node_modules/.npminstall/acorn/3.1.0/acorn/dist/acorn.js:330:12)
        at Parser.pp.parseExprSubscripts (/Users/Libbbbc/works/circle-web/node_modules/.npminstall/acorn/3.1.0/acorn/dist/acorn.js:225:19)
        at Parser.pp.parseMaybeUnary (/Users/Libbbbc/works/circle-web/node_modules/.npminstall/acorn/3.1.0/acorn/dist/acorn.js:204:17)
        at Parser.pp.parseExprOps (/Users/Libbbbc/works/circle-web/node_modules/.npminstall/acorn/3.1.0/acorn/dist/acorn.js:151:19)
        at Parser.pp.parseMaybeConditional (/Users/Libbbbc/works/circle-web/node_modules/.npminstall/acorn/3.1.0/acorn/dist/acorn.js:133:19)
        at Parser.pp.parseMaybeAssign (/Users/Libbbbc/works/circle-web/node_modules/.npminstall/acorn/3.1.0/acorn/dist/acorn.js:110:19)
        at Parser.pp.parseParenAndDistinguishExpression (/Users/Libbbbc/works/circle-web/node_modules/.npminstall/acorn/3.1.0/acorn/dist/acorn.js:373:28)
        at Parser.pp.parseExprAtom (/Users/Libbbbc/works/circle-web/node_modules/.npminstall/acorn/3.1.0/acorn/dist/acorn.js:304:19)
     @ ./webpack/javascripts/react/routes/web/dashboard/components/startups/detail/StartupsImgBlock.js 15:14-47
```

In my file 
```
import React, { Component } from 'react'
import Slider from 'react-slick/src/slider'
class User extends Component{
  render(){
    ......
  }
} 
```

**Comment by akiran** [comment]
This could be a problem with you webpack config
