### ISSUE TITLE
getting error while using react-slick with meteor

### ISSUE THREAD

**Issue by prateekkhanna12** [akiran/react-slick#798]
Errors prevented startup:

While processing files with ecmascript (for target web.browser):
native: Converting circular structure to JSON
  at Object.stringify (native)
  at Object.stringify (C:\Users\hp\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\core-js\modules\es6.symbol.js:224:23)
  at deepHash (C:\Users\hp\AppData\Local\.meteor\packages\ecmascript\0.8.1\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\util.js:27:18)
  at Object.exports.deepHash (C:\Users\hp\AppData\Local\.meteor\packages\ecmascript\0.8.1\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\util.js:42:10)
  at Cache.Cp.get (C:\Users\hp\AppData\Local\.meteor\packages\ecmascript\0.8.1\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\cache.js:66:22)
  at Object.compile (C:\Users\hp\AppData\Local\.meteor\packages\ecmascript\0.8.1\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\index.js:28:23)
  at Object.Babel.compile (packages/babel-compiler.js:54:29)
  at packages/babel-compiler.js:183:22
  at Function.time (C:\tools\tool-env\profile.js:305:10)
  at profile (packages/babel-compiler.js:226:20)
  at BabelCompiler.BCp.processOneFileForTarget (packages/babel-compiler.js:182:20)
  at BabelCompiler.<anonymous> (packages/babel-compiler.js:114:26)
  at Array.forEach (native)
  at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler.js:113:14)

Can anyone tell me why I am getting this error?

**Comment by lealexandre** [comment]
I have the same error. How did you fix this?

**Comment by vfonic** [comment]
+1
