### ISSUE TITLE
Causes weird issues when using in Nextjs web app along with react 16

### ISSUE THREAD

**Issue by santamaria7** [akiran/react-slick#909]
I am using this carousel in a web app alongside with nextjs and React 16 and I keep receiving weird errors:
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.
    at invariant (http://localhost:3000/_next/1510140110041/main.js:723:15)
    at createFiberFromElementType (http://localhost:3000/_next/1510140110041/commons.js:8191:5)
    at createFiberFromElement (http://localhost:3000/_next/1510140110041/commons.js:8136:15)
    at reconcileSingleElement (http://localhost:3000/_next/1510140110041/commons.js:9384:19)
    at reconcileChildFibers (http://localhost:3000/_next/1510140110041/commons.js:9483:35)
    at reconcileChildrenAtPriority (http://localhost:3000/_next/1510140110041/commons.js:10133:30)
    at reconcileChildren (http://localhost:3000/_next/1510140110041/commons.js:10124:5)
    at finishClassComponent (http://localhost:3000/_next/1510140110041/commons.js:10260:5)
    at updateClassComponent (http://localhost:3000/_next/1510140110041/commons.js:10232:12)
    at beginWork (http://localhost:3000/_next/1510140110041/commons.js:10611:16)
```

and sometimes: 
`Cannot read property 'toLowerCase' of undefined
TypeError: Cannot read property 'toLowerCase' of undefined
    at ReactDOMServerRenderer.renderDOM (D:\test\IranAppsNext\node_modules\react-dom\cjs\react-dom-server.node.development.js:2776:28)
    at ReactDOMServerRenderer.render (D:\test\IranAppsNext\node_modules\react-dom\cjs\react-dom-server.node.development.js:2755:23)
    at ReactDOMServerRenderer.read (D:\test\IranAppsNext\node_modules\react-dom\cjs\react-dom-server.node.development.js:2722:19)
    at renderToString (D:\test\IranAppsNext\node_modules\react-dom\cjs\react-dom-server.node.development.js:2980:25)
    at renderPage (D:\test\IranAppsNext\node_modules\next\dist\server\render.js:174:26)
    at Function.getInitialProps (D:\test\IranAppsNext\node_modules\next\dist\server\document.js:83:25)
    at _callee$ (D:\test\IranAppsNext\node_modules\next\dist\lib\utils.js:36:30)
    at tryCatch (D:\test\IranAppsNext\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (D:\test\IranAppsNext\node_modules\regenerator-runtime\runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (D:\test\IranAppsNext\node_modules\regenerator-runtime\runtime.js:117:21)`

The moment I comment the carousel section or exclude the containing component from my app everything is back to normal.

**Comment by fahimk** [comment]
Make sure your import statement is `import` Slider from 'react-slick';`

**Comment by santamaria7** [comment]
Thanks but the problem was not because of not importing the Slider component. There were some issues totally irrelevant to react-slick, which we found out later. That's why I closed the issue before receiving any answers. Thanks again.

**Comment by firestar300** [comment]
Same problem.
